AWSTemplateFormatVersion: '2010-09-09'
Resources:
  ExpensesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: expenses_table
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: expenseID
          AttributeType: S
      KeySchema:
        - AttributeName: expenseID
          KeyType: HASH
