AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 30
    MemorySize: 1024
    Runtime: java21
    Architectures: [ x86_64 ]

Resources:

  ExpensesApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: ExpensesApi
      StageName: Prod
      Cors:
        AllowMethods: "'GET,POST,OPTIONS'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"

  ExpensesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: expenses_table
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: expenseID
          AttributeType: S
        - AttributeName: expenseDate
          AttributeType: S   # OK si guardás Instant como ISO-8601 (String)
      KeySchema:
        - AttributeName: expenseID
          KeyType: HASH
        - AttributeName: expenseDate
          KeyType: RANGE
    DeletionPolicy: Retain

  ExpenseFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: com.aarmas.expenses_service.handler.ExpenseHandler
      Runtime: java21
      MemorySize: 1024
      Timeout: 30
      Environment:
        Variables:
          EXPENSES_TABLE: expenses_table
          SPRING_APPLICATION_JSON: '{"expenses":{"table":"expenses_table"}}'
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ExpensesTable
      Events:
        GetExpenses:
          Type: Api
          Properties:
            Path: /expenses
            Method: GET
            RestApiId: !Ref ExpensesApi
        CreateExpense:
          Type: Api
          Properties:
            Path: /expenses
            Method: POST
            RestApiId: !Ref ExpensesApi

  GatewayResponseDefault4XX:
    Type: AWS::ApiGateway::GatewayResponse
    Properties:
      ResponseType: DEFAULT_4XX
      RestApiId: !Ref ExpensesApi
      ResponseParameters:
        gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
        gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        gatewayresponse.header.Access-Control-Allow-Methods: "'GET,POST,OPTIONS'"

  GatewayResponseDefault5XX:
    Type: AWS::ApiGateway::GatewayResponse
    Properties:
      ResponseType: DEFAULT_5XX
      RestApiId: !Ref ExpensesApi
      ResponseParameters:
        gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
        gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        gatewayresponse.header.Access-Control-Allow-Methods: "'GET,POST,OPTIONS'"
